services:
  # --- Django backend ---
  cinema-backend:
    container_name: cinema-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Applying migrations...';
        poetry run python manage.py migrate &&
        echo 'Starting server...';
        poetry run python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      cinema-db:
        condition: service_healthy
    restart: unless-stopped

  # --- PostgreSQL database ---
  cinema-db:
    container_name: cinema-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # Ensure pg_isready checks the database that the image creates (POSTGRES_DB / POSTGRES_DATABASE)
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- pgAdmin UI ---
  pgadmin:
    container_name: cinema-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      # TODO - put it in ENV variables file or secret management system
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - cinema-db
      


volumes:
  db-data:
  pgadmin-data: